BEGIN TRANSACTION;


CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT NOT NULL UNIQUE,
	email TEXT NOT NULL UNIQUE,
	password TEXT NOT NULL,
	role TEXT NOT NULL,
	bio TEXT,
	avatar TEXT,
	status TEXT NOT NULL
);

COMMIT;